server:
  maxThreads: 1024
  applicationConnectors:
  - type: http
    port: 9000
    idleTimeout: 30 seconds
    useServerHeader: true
    useDateHeader: true
    idleTimeout: 30 seconds
    acceptorThreads: 10
    selectorThreads: 20
  adminConnectors:
  - type: http
    port: 9001
    idleTimeout: 30 seconds
    useServerHeader: true
    useDateHeader: true
    idleTimeout: 30 seconds
    acceptorThreads: 1
    selectorThreads: 2

logging:
  level: INFO
  loggers:
    "org.hibernate": ERROR
  appenders:
    - type: console
      logFormat: "%date %highlight(%-5level) [%thread] %cyan(%logger{10}) [%X{id}] %msg%n"
    - type: file
      currentLogFilename: /var/log/tracker/tracker.log
      archive: true
      archivedLogFilenamePattern: /var/log/tracker/tracker-%i.log.gz
      archivedFileCount: 10
      maxFileSize: 100MB
      timeZone: IST
      logFormat: "%date %level [%thread] %logger{10} [%X{id}] %msg%n\n"

trackerMasterDataSource:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: aditya123
  url: jdbc:mysql://localhost:3306/Tracker
  properties:
   charSet: UTF-8
   hibernate.show_sql: false
   hibernate.hbm2ddl.auto: validate
   hibernate.session.events.log: false
  maxWaitForConnection: 1s
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  minSize: 8
  maxSize: 256
  checkConnectionWhileIdle: false
  checkConnectionOnBorrow: true
  maxConnectionAge : 10s

#swagger:
#  resourcePackage: com.platform.resource
#rotationManagementConfig:
#  persistantFilePath: "/var/log/tracker/rotation_status.txt"