server:
  maxThreads: 1024
  applicationConnectors:
  - type: http
    port: 9000
    idleTimeout: 30 seconds
    useServerHeader: true
    useDateHeader: true
    idleTimeout: 30 seconds
    acceptorThreads: 10
    selectorThreads: 20
  adminConnectors:
  - type: http
    port: 9001
    idleTimeout: 30 seconds
    useServerHeader: true
    useDateHeader: true
    idleTimeout: 30 seconds
    acceptorThreads: 1
    selectorThreads: 2

  requestLog:
      enabled: true
      appenders:
        - type: file
          currentLogFilename: /var/log/tracker/requests.log
          archive: true
          archivedLogFilenamePattern: /var/log/tracker/requests-%d{yyyy-MM-dd}.log.gz
          archivedFileCount: 5
          timeZone: IST

logging:
  level: INFO
  loggers:
    "org.hibernate": ERROR
  appenders:
    - type: file
      currentLogFilename: /var/log/tracker/tracker.log
      archive: true
      archivedLogFilenamePattern: /var/log/tracker/tracker-%i.log.gz
      archivedFileCount: 10
      maxFileSize: 10MB
      timeZone: IST
      logFormat: "%date %level [%thread] %logger{10} [%X{id}] %msg%n\n"

trackerMasterDataSource:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: aditya123
  url: jdbc:mysql://localhost/Tracker?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  minSize: 8
  maxSize: 100
  properties:
      charSet: UTF-8
      hibernate.show_sql: false
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
      hibernate.hbm2ddl.auto: update
      hibernate.generate_statistics: false
      #hibernate.cache.use_second_level_cache: true
      #hibernate.cache.use_query_cache: true
      #hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      #net.sf.ehcache.configurationResourceName: config/ehcache.xml
  checkConnectionWhileIdle: false
  maxConnectionAge : 10s
  checkConnectionOnBorrow: true

#swagger:
#  resourcePackage: com.platform.resource

#rotationManagementConfig:
#  persistantFilePath: "/var/log/tracker/rotation_status.txt"